version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build-and-publish:
    executor: node/default
    working_directory: ~/project/RNTrueLayerPaymentsSDK
    parameters:
      isDryRun:
        type: boolean
        default: true
    steps:
      - checkout:
          path: ~/project
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Build SDK
          command: yarn build
      - run:
          name: Set npm version from git tag
          command: |
            GIT_TAG=$(git describe --tags --exact-match)
            if [ ! -z "$GIT_TAG" ]; then
              VERSION="${GIT_TAG}"
              npm version --no-git-tag-version $VERSION
            else
              echo "No git tag found. Exiting."
              exit 1
            fi
      - run:
          name: Publish to npm
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
            if << parameters.isDryRun >>; then
              npm publish --dry-run
            else
              npm publish
            fi

workflows:
  version: 2
  build-and-publish-workflow:
    jobs:
      - build-and-publish:
          name: build-and-publish-dry-run
          isDryRun: true
          filters: &main_and_semver_filters
            branches:
              only: main
            tags:
              only: /^(\d+\.){2}\d+$/
      - approval:
          type: approval
          requires:
            - build-and-publish-dry-run
          filters: *main_and_semver_filters
      - build-and-publish:
          name: build-and-publish-real
          isDryRun: false
          requires:
            - approval
          filters: *main_and_semver_filters
