/// The reasons for any errors that may occur while processing a single payment. These match the types in `types.ts`.
typedef NSString *RTNTrueLayerSinglePaymentErrorReason NS_TYPED_ENUM;
extern RTNTrueLayerSinglePaymentErrorReason const RTNTrueLayerSinglePaymentErrorReasonPaymentFailed;
extern RTNTrueLayerSinglePaymentErrorReason const RTNTrueLayerSinglePaymentErrorReasonCommunicationIssue;
extern RTNTrueLayerSinglePaymentErrorReason const RTNTrueLayerSinglePaymentErrorReasonUnknown;
extern RTNTrueLayerSinglePaymentErrorReason const RTNTrueLayerSinglePaymentErrorReasonConnectionSecurityIssue;
extern RTNTrueLayerSinglePaymentErrorReason const RTNTrueLayerSinglePaymentErrorReasonProcessorContextNotAvailable;
extern RTNTrueLayerSinglePaymentErrorReason const RTNTrueLayerSinglePaymentErrorReasonUserAborted;